#nullable enable
#if UNITY_EDITOR
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEditor;
using UnityEngine;

namespace UnityAngularBridge
{
    /// <summary>
    /// Generates unity-client.ts — a TypeScript class for calling Unity methods from Angular.
    /// Scans for [AngularExposed] methods and generates typed SendMessage wrappers.
    /// Methods with JsonType get a generated TS interface and a JSON.stringify wrapper.
    /// Supports XML doc → TSDoc and configurable output paths.
    /// </summary>
    [InitializeOnLoad]
    public class AngularExposedExport
    {
        private static readonly string _angularTsClientFileName = "unity-client.ts";
        private static readonly string _tabString = "  ";
        private static readonly Dictionary<string, string> _xmlDocs = new();

        static AngularExposedExport()
        {
            try
            {
                BridgeGeneratorUtilities.LoadXmlDocumentation(_xmlDocs);
                GenerateUnityClient();
            }
            catch (Exception e)
            {
                Debug.LogError($"[UnityAngularBridge] unity-client.ts generation failed: {e}");
            }
        }

        private class ExposedMethod
        {
            public string GameObjectName = string.Empty;
            public string MethodName = string.Empty;
            public string Documentation = string.Empty;
            public string ParameterType = string.Empty;
            public string ParameterName = string.Empty;
            public Type? JsonType;
        }

        #region Scanning

        private static List<ExposedMethod> ScanMethods()
        {
            List<ExposedMethod> methods = new();
            Assembly assembly = Assembly.GetExecutingAssembly();
            IEnumerable<Type> publicClasses = assembly.GetExportedTypes().Where(p => p.IsClass);

            foreach (Type type in publicClasses)
            {
                IEnumerable<MethodInfo> methodInfos = type
                    .GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Static)
                    .Where(m => m.GetCustomAttributes(typeof(AngularExposedAttribute), false).Length > 0);

                foreach (MethodInfo methodInfo in methodInfos)
                {
                    AngularExposedAttribute attribute = methodInfo.GetCustomAttribute<AngularExposedAttribute>()!;

                    ExposedMethod method = new()
                    {
                        GameObjectName = attribute.GameObjectName,
                        MethodName = methodInfo.Name,
                        JsonType = attribute.JsonType,
                    };

                    // Get documentation: attribute override > XML docs
                    method.Documentation = !string.IsNullOrEmpty(attribute.Documentation)
                        ? attribute.Documentation
                        : BridgeGeneratorUtilities.GetXmlDocumentation(_xmlDocs, type, methodInfo);

                    ParameterInfo[] parameters = methodInfo.GetParameters();
                    if (parameters.Length > 1)
                    {
                        throw new InvalidOperationException($"Method {method.MethodName} is only allowed to have 1 argument");
                    }

                    if (method.JsonType != null)
                    {
                        if (parameters.Length != 1 || parameters[0].ParameterType != typeof(string))
                        {
                            throw new InvalidOperationException(
                                $"[UnityAngularBridge] Method {method.MethodName} declares JsonType and must take exactly one string parameter " +
                                $"(deserialize it with JsonUtility.FromJson<{method.JsonType.Name}>).");
                        }
                        method.ParameterType = method.JsonType.Name;
                        method.ParameterName = parameters[0].Name ?? "request";
                    }
                    else if (parameters.Length == 1)
                    {
                        method.ParameterType = ParameterTypeToTypescriptType(parameters[0].ParameterType);
                        method.ParameterName = parameters[0].Name ?? "data";
                    }

                    methods.Add(method);
                }
            }

            return methods;
        }

        #endregion

        #region GenerateUnityClient

        private static void GenerateUnityClient()
        {
            List<ExposedMethod> methods = ScanMethods();
            string importPath = UnityAngularBridgeSettings.GetIUnityInstanceImportPath();

            using StringWriter stringWriter = new();
            using (IndentedTextWriter writer = new(stringWriter, _tabString))
            {
                AddAutoGeneratedFileCommentLines(writer);
                AddImportLines(writer, importPath);
                TypeScriptInterfaceGenerator.WriteInterfaces(
                    writer,
                    methods.Where(m => m.JsonType != null).Select(m => m.JsonType!).Distinct());
                AddClassOpeningLines(writer);

                foreach (ExposedMethod method in methods)
                {
                    AddMethodLines(writer, method);
                }

                AddClassClosingLines(writer);

                if (string.IsNullOrEmpty(importPath))
                {
                    AddIUnityInstanceInterfaceLines(writer);
                }
            }

            string outputPath = UnityAngularBridgeSettings.GetUnityClientOutputPath();
            BridgeGeneratorUtilities.WriteFileIfChanged(
                Path.Combine(outputPath, _angularTsClientFileName), stringWriter.ToString());
        }

        private static void AddAutoGeneratedFileCommentLines(IndentedTextWriter writer)
        {
            writer.WriteLine("//----------------------");
            writer.WriteLine("// <auto-generated>");
            writer.WriteLine("//    Generated using AngularExposedExport.cs in UnityAngularBridge project.");
            writer.WriteLine("// </auto-generated>");
            writer.WriteLine("//----------------------");
            writer.WriteLine(string.Empty);
            writer.WriteLine("/* eslint-disable */");
            writer.WriteLine(string.Empty);
        }

        private static void AddImportLines(IndentedTextWriter writer, string importPath)
        {
            writer.WriteLine("import { Injectable } from \"@angular/core\";");
            if (!string.IsNullOrEmpty(importPath))
            {
                writer.WriteLine($"import type {{ IUnityInstance }} from \"{importPath}\";");
                writer.WriteLine(string.Empty);
                writer.WriteLine("export type { IUnityInstance };");
            }
            writer.WriteLine(string.Empty);
        }

        private static void AddClassOpeningLines(IndentedTextWriter writer)
        {
            writer.WriteLine("@Injectable()");
            writer.WriteLine("export class UnityClient {");
            writer.Indent++;
        }

        private static void AddMethodLines(IndentedTextWriter writer, ExposedMethod method)
        {
            string gameObjectName = method.GameObjectName;
            string methodName = method.MethodName;
            bool hasParameter = !string.IsNullOrEmpty(method.ParameterName);

            if (!string.IsNullOrEmpty(method.Documentation))
            {
                writer.WriteLine($"/** {method.Documentation} */");
            }

            if (hasParameter)
            {
                string argument = method.JsonType != null
                    ? $"JSON.stringify({method.ParameterName})"
                    : method.ParameterName;

                writer.WriteLine($"public {BridgeGeneratorUtilities.FirstCharToLowerCase(gameObjectName)}_{methodName}(unityInstance: IUnityInstance, {method.ParameterName}: {method.ParameterType}): void {{");
                writer.Indent++;
                writer.WriteLine($"unityInstance?.SendMessage(\"{gameObjectName}\", \"{methodName}\", {argument});");
                writer.Indent--;
                writer.WriteLine("}");
                writer.WriteLine(string.Empty);
            }
            else
            {
                writer.WriteLine($"public {BridgeGeneratorUtilities.FirstCharToLowerCase(gameObjectName)}_{methodName}(unityInstance: IUnityInstance): void {{");
                writer.Indent++;
                writer.WriteLine($"unityInstance?.SendMessage(\"{gameObjectName}\", \"{methodName}\");");
                writer.Indent--;
                writer.WriteLine("}");
                writer.WriteLine(string.Empty);
            }
        }

        private static void AddClassClosingLines(IndentedTextWriter writer)
        {
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine(string.Empty);
        }

        private static void AddIUnityInstanceInterfaceLines(IndentedTextWriter writer)
        {
            writer.WriteLine("export interface IUnityInstance {");
            writer.Indent++;
            writer.WriteLine("SendMessage(gameObjectName: string, methodName: string, data?: unknown): void;");
            writer.WriteLine("SetFullscreen(value: number): void;");
            writer.WriteLine("Quit(): Promise<unknown>;");
            writer.Indent--;
            writer.WriteLine("}");
        }

        #endregion

        #region TypeConversion

        private static string ParameterTypeToTypescriptType(object parameterType)
        {
            return parameterType.ToString() switch
            {
                "System.String" => "string",
                "System.Int32" => "number",
                "System.Single" => "number",
                _ => throw new InvalidOperationException(
                    $"ParameterType {parameterType} is not supported. Only string and number variants are allowed."),
            };
        }

        #endregion
    }
}
#endif
