import { computed, inject, Injectable, signal } from '@angular/core';
import type { IUnityInstance } from 'ngx-unity';
import { SpawnRequest, UnityClient } from '../generated/unity-client';
import { UnityJSLibExportedService } from '../generated/unity-jslib-exported.service';

/**
 * Wraps the generated Unity bridge files with Angular Signals and Computed values.
 *
 * - `UnityClient` (generated by AngularExposedExport.cs) provides methods to call Unity.
 * - `UnityJSLibExportedService` (generated by JSLibExport.cs) provides signals for Unity events.
 *
 * Since the generated service now exposes signals directly, no RxJS conversion is needed.
 */
@Injectable({ providedIn: 'root' })
export class UnityBridgeService {
  private readonly unityClient = inject(UnityClient);
  private readonly jsLibService = inject(UnityJSLibExportedService);

  // ----- Unity instance reference -----
  private readonly _unityInstance = signal<IUnityInstance | null>(null);
  readonly unityInstance = this._unityInstance.asReadonly();

  // ----- Signals from Unity events (Unity → Angular via JSLib) -----
  readonly selectedObject = this.jsLibService.sendSelectedObject;
  readonly objectsList = this.jsLibService.sendObjectsList;
  readonly sceneState = this.jsLibService.sendSceneState;

  // ----- Computed signals -----
  readonly objectCount = computed(() => this.objectsList().length);
  readonly hasSelection = computed(() => !!this.selectedObject());
  readonly isConnected = computed(() => !!this.unityInstance());

  constructor() {
    // Register callback handler for Unity data requests
    this.jsLibService.registerRequestDataFromWebHandler((query, respond) => {
      console.log(`[UnityBridge] Data request from Unity: ${query}`);
      respond(`Result for: ${query}`);
    });
  }

  /** Set the Unity instance (called after Unity finishes loading). */
  setUnityInstance(instance: IUnityInstance): void {
    this._unityInstance.set(instance);
  }

  // ----- Angular → Unity methods (via AngularExposed / UnityClient) -----

  loadObject(objectId: string): void {
    const instance = this._unityInstance();
    if (instance) {
      this.unityClient.sceneManager_LoadObject(instance, objectId);
    }
  }

  setColor(colorHex: string): void {
    const instance = this._unityInstance();
    if (instance) {
      this.unityClient.sceneManager_SetColor(instance, colorHex);
    }
  }

  toggleVisibility(): void {
    const instance = this._unityInstance();
    if (instance) {
      this.unityClient.sceneManager_ToggleVisibility(instance);
    }
  }

  resetScene(): void {
    const instance = this._unityInstance();
    if (instance) {
      this.unityClient.sceneManager_ResetScene(instance);
    }
  }

  /** Spawn a new object in the scene from a typed request (sent to Unity as JSON). */
  spawnObject(request: SpawnRequest): void {
    const instance = this._unityInstance();
    if (instance) {
      this.unityClient.sceneManager_SpawnFromJson(instance, request);
    }
  }

  /** Send a navigation change to Unity (invokes registered callback). */
  sendNavigationChange(route: string): void {
    this.jsLibService.notifyOnNavigationChanged(route);
  }
}
